#!/usr/bin/env python3
"""
Strip preview images from grid_mesh_library.tres to reduce file size

Purpose: Godot MeshLibrary files contain embedded preview thumbnails as
PackedByteArray data, making them huge (99KB → 3KB after stripping).
These previews are auto-generated by Godot editor and don't need to be
in version control.

Usage:
    python3 _claude_scripts/strip_mesh_library_previews.py

This script:
1. Reads assets/grid_mesh_library.tres
2. Removes [sub_resource type="Image"] blocks (contain byte arrays)
3. Removes [sub_resource type="ImageTexture"] blocks (reference images)
4. Removes item/N/preview assignments
5. Cleans up extra blank lines
6. Writes back to the same file

Run this before committing changes to grid_mesh_library.tres to keep
the file manageable in git diffs.

Note: Godot will regenerate previews when you open the file in the editor,
so you'll need to run this script again before each commit if you've edited
the MeshLibrary in Godot.
"""

import re
import os

def strip_preview_images(tres_path):
    """Remove embedded preview image data from a MeshLibrary .tres file"""

    if not os.path.exists(tres_path):
        print(f"❌ Error: File not found: {tres_path}")
        return False

    # Read the file
    with open(tres_path, 'r') as f:
        content = f.read()

    original_size = len(content)

    # Remove Image sub-resources (contain huge PackedByteArray data)
    # Pattern: [sub_resource type="Image" ...] followed by all its data until next section
    content = re.sub(
        r'\[sub_resource type="Image"[^\]]*\][^\[]*',
        '',
        content,
        flags=re.DOTALL
    )

    # Remove ImageTexture sub-resources (reference the stripped Images)
    content = re.sub(
        r'\[sub_resource type="ImageTexture"[^\]]*\][^\[]*',
        '',
        content,
        flags=re.DOTALL
    )

    # Remove preview assignments from MeshLibrary items
    # Pattern: item/0/preview = SubResource("...")
    content = re.sub(
        r'^item/\d+/preview = .*$',
        '',
        content,
        flags=re.MULTILINE
    )

    # Clean up multiple consecutive blank lines (leave max 2)
    content = re.sub(r'\n{3,}', '\n\n', content)

    # Write back
    with open(tres_path, 'w') as f:
        f.write(content)

    new_size = len(content)
    saved_bytes = original_size - new_size
    saved_percent = (saved_bytes / original_size) * 100 if original_size > 0 else 0

    print(f"✓ Stripped preview images from {tres_path}")
    print(f"  Original size: {original_size:,} bytes")
    print(f"  New size: {new_size:,} bytes")
    print(f"  Saved: {saved_bytes:,} bytes ({saved_percent:.1f}%)")

    return True

if __name__ == '__main__':
    # Default path relative to project root
    tres_path = 'assets/grid_mesh_library.tres'

    success = strip_preview_images(tres_path)
    exit(0 if success else 1)
